### ISSUE TITLE
JDBCBackend.__del__ is noisy on Windows

### ISSUE THREAD

**Issue by khaeru** [iiasa/ixmp#201]
@GamzeUnlu95 reports the following:
```
Exception ignored in: <function JDBCBackend.__del__ at 0x0000028D9F015400>
Traceback (most recent call last):
 File "c:\users\unlu\documents\github\ixmp\ixmp\backend\jdbc.py", line 210, in __del__
   Path(self._properties_file).unlink()
 File "C:\Users\unlu\AppData\Local\Continuum\anaconda3\lib\pathlib.py", line 1287, in unlink
   self._accessor.unlink(self)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\unlu\\AppData\\Local\\Temp\\tmp_s2qwnou.properties'
```

This is because the destructor (__del__) of JDBCBackend is trying to remove the temporary properties file: https://github.com/iiasa/ixmp/blob/952d1345c7df6e8b79ce64e4333847b39f7bfb79/ixmp/backend/jdbc.py#L208-L212

The solution is probably to call .close_db() before removing the file.

**Comment by khaeru** [comment]
This was also reported by @Jihoon.

@zikolach commented that this can probably be fixed by a change in ixmp_source: add a new constructor for the Java Platform class which takes the four arguments (driver, URL, username, password) directly. Then the Python JDBCBackend could simply pass these values, instead of writing them to a file.
