### ISSUE TITLE
Reporting exception handling doesn't work in Jupyter

### ISSUE THREAD

**Issue by khaeru** [iiasa/ixmp#208]
As reported by @Jihoon: in Jupyter kernels, the ixmp.reporting exception-handling code produces unhelpful tracebacks like the following:
```
rep.get(rep.full_key('emission_factor'))

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3343, in run_code
    self.showtraceback(running_compiled_code=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2045, in showtraceback
    self._showtraceback(etype, value, stb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 546, in _showtraceback
    u'evalue' : py3compat.safe_unicode(evalue),
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipython_genutils\py3compat.py", line 65, in safe_unicode
    return unicode_type(e)
  File "h:\mydocuments\message\ixmp\ixmp\reporting\__init__.py", line 667, in __str__
    tb = TracebackException.from_exception(self.cause, capture_locals=True)
  File "C:\ProgramData\Anaconda3\lib\traceback.py", line 526, in from_exception
    return cls(type(exc), exc, exc.__traceback__, *args, **kwargs)

AttributeError: 'NoneType' object has no attribute '__traceback__'
```

This is contrary to its goal of providing intelligible messages when `.get()` fails.

**Comment by khaeru** [comment]
Sorry for the confusion—this is a duplicate of #206.
