### ISSUE TITLE
ixmp should accept filters with non-elements of index sets

### ISSUE THREAD

**Issue by khaeru** [iiasa/ixmp#216]
@OFR-IIASA reports that, after #213, code in message_data causes exceptions like the following:
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\mix-data-script.py", line 11, in <module>
    load_entry_point('message-data', 'console_scripts', 'mix-data')()
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "c:\repo\message_data_clean\message_data\model\__init__.py", line 82, in run
    main(context)
  File "c:\repo\message_data_clean\message_data\model\runscript.py", line 174, in main
    sr.run_all()
  File "c:\repo\message_data_clean\message_data\model\scenario_runner.py", line 139, in run_all
    **args)
  File "c:\repo\message_data_clean\message_data\model\scenario_runner.py", line 190, in run
    biomass_trade=self.biomass_trade, biomass='rhs')
  File "c:\repo\message_data_clean\message_data\scenario_generation\policies\add_indcs.py", line 461, in __init__
    tec_data, reg_tecs = self.retrv_tec_data(ds_baseline, all_tecs)
  File "c:\repo\message_data_clean\message_data\scenario_generation\policies\add_indcs.py", line 1497, in retrv_tec_data
    tec], 'level': ['resource', 'primary', 'secondary', 'final', 'useful']}, formatting='reporting').reset_index().drop('Mode', axis=1)
  File "c:\repo\message_data_clean\message_data\tools\post_processing\pp_utils.py", line 1037, in _retr_io_data
    df = ds.par(param, filter)
  File "c:\repo\ixmp\ixmp\core.py", line 928, in par
    result = self._backend('item_get_elements', 'par', name, filters)
  File "c:\repo\ixmp\ixmp\core.py", line 358, in _backend
    return self.platform._backend(self, method, *args, **kwargs)
  File "c:\repo\ixmp\ixmp\backend\base.py", line 25, in __call__
    return getattr(self, method)(obj, *args, **kwargs)
  File "c:\repo\ixmp\ixmp\backend\jdbc.py", line 523, in item_get_elements
    jList = item.getElements(jFilter)
jpype._jclass.IxException: at.ac.iiasa.ixmp.exceptions.IxException: The index set 'technology' does not have an element 'oil_extr_8'!
```

In short:
- The ixmp_source method `item.getElements(jFilter)` expects that filters will *only* contain values which are members/elements of the corresponding index set(s).
- `ixmp.utils.filtered()` uses pandas' `isin(...)` method, and so non-member elements are permissible; they simply have no effect.
- Previously, when Scenario objects were created with `cache=True`, the entire parameter was read (i.e. without any jFilter), and *then* `filtered()` was applied.
- The effect was that user code (e.g. message_data) could include non-member elements.
- With #213, the Java-side filtering is used more often. Since this code is more picky than `filtered()`, it raises these exceptions.

There were no tests for this desired discrepancy between the Java-side and Python-side behaviour.

The fix is for JDBCBackend to silently remove any non-members of sets before creating the jFilter.

**Comment by danielhuppmann** [comment]
don't quite agree that this is a bug - this sanity check was inserted into the Java code on purpose to ensure that filters are meaningful.

**Comment by khaeru** [comment]
> don't quite agree that this is a bug - this sanity check was inserted into the Java code on purpose to ensure that filters are meaningful.

I don't have an opinion either way. The bug from my POV is that we had expected behaviour that was not tested; I changed something, tests passed, then later I was surprised to learn the code was not usable.

@OFR-IIASA indicated that ensuring "meaningful" filters across message_data is too onerous at this moment. One example was: code that handles SSP1, SSP2, and SSP3 versions of MESSAGE-GLOBIOM works with a single list of technologies; but the different versions of the model have more or fewer technologies. So all such code would need to tailor itself to the SSP version; or the sets would have to be augmented without adding parameter values, etc.

I'm happy to either merge #217 or close it without merging, depending on what consensus is reached.

**Comment by danielhuppmann** [comment]
A better way to kill the loud exception is to remove the following section in the Java source code: https://github.com/iiasa/ixmp_source/blob/abcbf52548d93e99bd171631008780d428c783e4/src/main/java/at/ac/iiasa/ixmp/objects/Item.java#L418

**Comment by khaeru** [comment]
> A better way to kill the loud exception is to remove the following section in the Java source code: https://github.com/iiasa/ixmp_source/blob/abcbf52548d93e99bd171631008780d428c783e4/src/main/java/at/ac/iiasa/ixmp/objects/Item.java#L418

If that's the consensus and someone wants to do that, it would be great. The changes to JDBCBackend could then be removed from #217. The new test should still be merged, because other Backends that don't use ixmp_source should behave the same way.
