### ISSUE TITLE
`message-ix show-versions` raises TypeError

### ISSUE THREAD

**Issue by khaeru** [iiasa/ixmp#338]
Reported by @volker-krey in https://github.com/iiasa/message_ix/issues/364#issuecomment-645928395:

#### Code sample or context

> I tried to follow the updated instructions which seem to work, but `message-ix show-versions` fails due to a type mismatch (see end of traceback output below).

#### Expected result

Version information is shown.

#### Problem description

> fails due to a type mismatch (see end of traceback output below).

```
Traceback (most recent call last):
  File "C:\Users\krey\anaconda3\envs\message\Scripts\message-ix-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\krey\anaconda3\envs\message\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\krey\anaconda3\envs\message\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\krey\anaconda3\envs\message\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\krey\anaconda3\envs\message\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\krey\anaconda3\envs\message\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\krey\anaconda3\envs\message\lib\site-packages\ixmp\cli.py", line 101, in show_versions_cmd
    ixmp.show_versions()
  File "C:\Users\krey\anaconda3\envs\message\lib\site-packages\ixmp\utils.py", line 377, in show_versions
    gl = _git_log(mod)
  File "C:\Users\krey\anaconda3\envs\message\lib\site-packages\ixmp\utils.py", line 343, in _git_log
    cwd = Path(mod.__file__).parent
  File "C:\Users\krey\anaconda3\envs\message\lib\pathlib.py", line 1038, in __new__
    self = cls._from_parts(args, init=False)
  File "C:\Users\krey\anaconda3\envs\message\lib\pathlib.py", line 679, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "C:\Users\krey\anaconda3\envs\message\lib\pathlib.py", line 663, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by khaeru** [comment]
The lines:
```
File "C:\Users\krey\anaconda3\envs\message\lib\site-packages\ixmp\utils.py", line 343, in _git_log
    cwd = Path(mod.__file__).parent
```
…indicate that something is going wrong while it tries to check whether you've got ixmp, message_ix, or message_data installed from source.

@volker-krey, could you mention whether you have `git` installed on the machine you're using?

**Comment by volker-krey** [comment]
`git` is installed and can also be executed successfully in `anaconda prompt`.  Also, the other recommended check in the updated installation instructions `message-ix --platform=default list` executes without any error messages.

**Comment by khaeru** [comment]
Thanks for the info. I think the way Python tries to call `git` to get the commit log just isn't working; this would only affect the `show-version` command and not `list`. I'll add something to catch that exception.

**Comment by zsalimian** [comment]
Would you please help me about the above error
$message-ix show-versions fails due to the error in the attached picture
Would you please tell me how did you solve it?
![Untitled](https://user-images.githubusercontent.com/71164512/97077803-8656be00-15f3-11eb-8660-37389b3730c4.png)

**Comment by khaeru** [comment]
@zsalimian your message shows (in the last line): `JVMNotSupportedException` and gives the message "JVM mismatch, python is 64 bit and JVM is 32 bit."

As the message explains, the cause is probably that you have installed a 32-bit version of Java. You need to have a 64-bit installation to go with your 64-bit Python installation.

Also:
- This is different from the current issue, which is about a `TypeError`. Please open a new issue in the future, instead of commenting on an unrelated issue.
- Please read the [GitHub formatting help](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/basic-writing-and-formatting-syntax) and try to paste future error messages as text:
  ```
  Traceback (most recent call last):
  ...
  ```
  …instead of as a screenshot.
