### ISSUE TITLE
scenario.add_par returns fatal error (java.lang.OutOfMemoryError)

### ISSUE THREAD

**Issue by DIUANA** [iiasa/ixmp#348]
#### Code sample or context

I am working on a model with large data and I am not able to use ixmp to generate the gdx file.

When I try to add all parameters I got an error regardless the order I try to add them.

This error is related to java.lang.OutOfMemoryError: Java heap space despite the fact CPU memory is not even close to reach the maximum.

```
for p in par_list_dic.keys():
    print('\n...'+p+' ---> Loading...')
    print(list(scenario.idx_names(p)))
    print(par_list_dic[p].columns.tolist())
    tmp_name = list(scenario.idx_names(p)) + ['value']
    tmp_par = par_list_dic[p]
    #print('tmp_name:\n')
    #print(tmp_name)
    #print('cols:\n')
    #print(list(tmp_par.columns))
    tmp_par.columns = tmp_name
    tmp_par['unit'] = '-'
    scenario.add_par(p, tmp_par)
    par_list_dic[p] = None
```

#### Expected result

I was expecting to finish this process but I got a fatal error message about java running out of memory. The main issue here is that CPU memory is not reaching much more than 60% at any moment during this action. Is there any work around to deal with this java problem?

#### Problem description

```
Exception: Java Exception


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "<ipython-input-68-dfa0b6b35c36>", line 15, in <module>
    scenario.add_par(p, tmp_par)

  File "d:\fabio\diuana_pdrive_iiasa\models\ixmp\ixmp\core.py", line 1264, in add_par
    self._backend('item_set_elements', 'par', name, elements)

  File "d:\fabio\diuana_pdrive_iiasa\models\ixmp\ixmp\core.py", line 473, in _backend
    return self.platform._backend(self, method, *args, **kwargs)

  File "d:\fabio\diuana_pdrive_iiasa\models\ixmp\ixmp\backend\base.py", line 22, in __call__
    return getattr(self, method)(obj, *args, **kwargs)

  File "d:\fabio\diuana_pdrive_iiasa\models\ixmp\ixmp\backend\jdbc.py", line 844, in item_set_elements
    args = [to_jlist(key)] if key else []

  File "d:\fabio\diuana_pdrive_iiasa\models\ixmp\ixmp\backend\jdbc.py", line 1057, in to_jlist
    jlist.addAll(arg)

  File "D:\ProgFile\Anaconda3\envs\MSG\lib\site-packages\jpype\_jcollection.py", line 248, in _JSequenceConvert
    return _jclass.JClass('java.util.Arrays').asList(obj)

java.lang.OutOfMemoryError: java.lang.OutOfMemoryError: Java heap space
```

![image](https://user-images.githubusercontent.com/37837898/87430947-4c215d80-c5bc-11ea-95e3-e1f46c691fc9.png)

#### Versions

<details><summary>Output of <tt>ixmp show-versions</tt></summary>

```
ixmp.__version__
'3.0.1.dev44+gddbe600'
```

</details>

**Comment by khaeru** [comment]
> model with large data

How large?

> memory is not reaching much more than 60% at any moment during this action.

Memory can still be exhausted in this situation, depending on the maximum size of the Java heap, and how big the object is that you are asking the Java code to instantiate.

Have you tried using the `-Xmx…` argument to the JVM (i.e. `jvmargs=['-Xmx4G']` or some other value; see [here](CPU memory is not reaching much more than 60% at any moment during this action)) to set a larger heap size?

**Comment by DIUANA** [comment]
Thanks for responding me Paul.

When I generate the gdx mannualy it has 130 Mb. I think I have heard about larger gdx files at IIASA.

I tried to implement the parameter you have suggested but I got an error.

`mp = ixmp.Platform(jvmargs=['-Xmx4G'])`

```
Traceback (most recent call last):

  File "d:\fabio\diuana_pdrive_iiasa\models\ixmp\ixmp\backend\jdbc.py", line 80, in _create_properties
    properties.setProperty('jdbc.driver', DRIVER_CLASS[driver])

KeyError: None


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-9-1257f3eac3ab>", line 1, in <module>
    mp = ixmp.Platform(jvmargs=['-Xmx4G'])

  File "d:\fabio\diuana_pdrive_iiasa\models\ixmp\ixmp\core.py", line 97, in __init__
    self._backend = backend_class(**kwargs)

  File "d:\fabio\diuana_pdrive_iiasa\models\ixmp\ixmp\backend\jdbc.py", line 227, in __init__
    properties = _create_properties(**kwargs)

  File "d:\fabio\diuana_pdrive_iiasa\models\ixmp\ixmp\backend\jdbc.py", line 83, in _create_properties
    f'unrecognized/unsupported JDBC driver {repr(driver)}'

ValueError: unrecognized/unsupported JDBC driver None
```

I also tried 2 different approaches but they did not work. 
```
mp.jdbc.start_jvm(jvmargs=['-Xmx4G'])
mp.backend.jdbc.JDBCBackend(jvmargs=['-Xmx4G'])
```

How should I set it?

**Comment by khaeru** [comment]
> > How large?
>
> When I generate the gdx mannualy it has 130 Mb. I think I have heard about larger gdx files at IIASA.

Sorry, to be more precise: _how many rows/entries_ are in the data frame which you are trying to pass to `.add_par()`?

> I tried to implement the parameter you have suggested but I got an error.
> ```
> mp = ixmp.Platform(jvmargs=['-Xmx4G'])
> ```
> How should I set it?

The error here is you are not specifying _which_ platform/database you want to connect to. You will always need to do this; `jvmargs` is an _additional_ argument that specifies how much memory the Java side may use.

So, for instance:
```
mp = ixmp.Platform(name='myplatform', jvmargs=['-Xmx4G'])
```
…if 'myplatform' (or 'default', or something else) is one of the JDBC platforms configured on your system.

**Comment by DIUANA** [comment]
Thanks again Paul

The model has 20 parameters and a total of 8950910 rows summing all parameters.

Implementing the` jvmargs=['-Xmx4G']` I could add all parmeters however when I try to commit the scenario `scenario.commit(comment='TEST')` I get the memory error. Same case as before the CPU memory is not reaching much more than 60%.

Any additional thoughts about how to deal with it?

All the Best

```
  File "DbDAO.java", line 1646, in at.ac.iiasa.ixmp.database.DbDAO.writeInputStream

  File "ObjectOutputStream.java", line 348, in java.io.ObjectOutputStream.writeObject

  File "ObjectOutputStream.java", line 1178, in java.io.ObjectOutputStream.writeObject0

  File "ObjectOutputStream.java", line 1432, in java.io.ObjectOutputStream.writeOrdinaryObject

  File "ObjectOutputStream.java", line 1496, in java.io.ObjectOutputStream.writeSerialData

  File "ObjectStreamClass.java", line 1140, in java.io.ObjectStreamClass.invokeWriteObject

  File "Method.java", line 498, in java.lang.reflect.Method.invoke

  File "DelegatingMethodAccessorImpl.java", line 43, in sun.reflect.DelegatingMethodAccessorImpl.invoke

  File "sun.reflect.GeneratedMethodAccessor4.java", line -1, in sun.reflect.GeneratedMethodAccessor4.invoke

  File "ArrayList.java", line 766, in java.util.ArrayList.writeObject

  File "ObjectOutputStream.java", line 348, in java.io.ObjectOutputStream.writeObject

  File "ObjectOutputStream.java", line 1178, in java.io.ObjectOutputStream.writeObject0

  File "ObjectOutputStream.java", line 1432, in java.io.ObjectOutputStream.writeOrdinaryObject

  File "ObjectOutputStream.java", line 1509, in java.io.ObjectOutputStream.writeSerialData

  File "ObjectOutputStream.java", line 1548, in java.io.ObjectOutputStream.defaultWriteFields

  File "ObjectOutputStream.java", line 1178, in java.io.ObjectOutputStream.writeObject0

  File "ObjectOutputStream.java", line 1432, in java.io.ObjectOutputStream.writeOrdinaryObject

  File "ObjectOutputStream.java", line 1496, in java.io.ObjectOutputStream.writeSerialData

  File "ObjectStreamClass.java", line 1140, in java.io.ObjectStreamClass.invokeWriteObject

  File "Method.java", line 498, in java.lang.reflect.Method.invoke

  File "DelegatingMethodAccessorImpl.java", line 43, in sun.reflect.DelegatingMethodAccessorImpl.invoke

  File "sun.reflect.GeneratedMethodAccessor3.java", line -1, in sun.reflect.GeneratedMethodAccessor3.invoke

  File "Vector.java", line 1103, in java.util.Vector.writeObject

  File "ObjectOutputStream.java", line 482, in java.io.ObjectOutputStream.writeFields

  File "ObjectOutputStream.java", line 1707, in java.io.ObjectOutputStream$PutFieldImpl.writeFields

  File "ObjectOutputStream.java", line 162, in java.io.ObjectOutputStream.access$300

  File "ObjectOutputStream.java", line 1174, in java.io.ObjectOutputStream.writeObject0

  File "ObjectOutputStream.java", line 1378, in java.io.ObjectOutputStream.writeArray

  File "ObjectOutputStream.java", line 1178, in java.io.ObjectOutputStream.writeObject0

  File "ObjectOutputStream.java", line 1428, in java.io.ObjectOutputStream.writeOrdinaryObject

  File "ObjectOutputStream.java", line 2276, in java.io.ObjectOutputStream$HandleTable.assign

  File "ObjectOutputStream.java", line 2347, in java.io.ObjectOutputStream$HandleTable.growEntries

Exception: Java Exception


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "<ipython-input-3-2f0635388c80>", line 462, in <module>
    scenario.commit(comment='BLUES_LB_TEST')

  File "d:\fabio\diuana_pdrive_iiasa\models\ixmp\ixmp\core.py", line 516, in commit
    self._backend('commit', comment)

  File "d:\fabio\diuana_pdrive_iiasa\models\ixmp\ixmp\core.py", line 473, in _backend
    return self.platform._backend(self, method, *args, **kwargs)

  File "d:\fabio\diuana_pdrive_iiasa\models\ixmp\ixmp\backend\base.py", line 22, in __call__
    return getattr(self, method)(obj, *args, **kwargs)

  File "d:\fabio\diuana_pdrive_iiasa\models\ixmp\ixmp\backend\jdbc.py", line 548, in commit
    self.jindex[ts].commit(comment)

java.lang.OutOfMemoryError: java.lang.OutOfMemoryError: Java heap space
```

**Comment by khaeru** [comment]
> Implementing the `jvmargs=['-Xmx4G']`
>
> Any additional thoughts about how to deal with it?

You should try not just the single value, but a range of different values. This is a system-specific: it depends on the amount of memory you have on your system, your OS, etc. If it exhausts 4 GiB of heap space while your system memory usage is only at 60%, that indicates you might have ~8 GiB or more on your system, so you could try specifying that much, or intermediate values.

If you can't find any value that works, please report all the values you've tried, as well as how much memory you have on your system.

**Comment by DIUANA** [comment]
Hi Paul.

I made it work. Thanks for helping me out.

All the Best
