### ISSUE TITLE
Oracle error when trying to update timeseries

### ISSUE THREAD

**Issue by OFR-IIASA** [iiasa/ixmp#67]
If timeseries have already been uploaded e.g. for 1990 to 2110, and the same timeseries are then updated e.g. for 2020-2100 then the following error occurs:

2018-07-06 09:54:39,554 ERROR at.ac.iiasa.ixmp.database.DbDAO:766 - Error writing the timeseries data to the IXMP database!
java.sql.BatchUpdateException: ORA-00001: unique constraint (ENE_IXMP.SYS_C0065938) violated

        at oracle.jdbc.driver.OraclePreparedStatement.executeBatch(OraclePreparedStatement.java:12296)
        at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:246)
        at at.ac.iiasa.ixmp.database.OracleDAO.saveTimeseriesToDB(OracleDAO.java:187)
        at at.ac.iiasa.ixmp.objects.Scenario.commit(Scenario.java:2014)
        at at.ac.iiasa.ixmp.objects.Scenario.commit(Scenario.java:1906)
        at at.ac.iiasa.ixmp.objects.MsgScenario.commit(MsgScenario.java:1316)
        at at.ac.iiasa.ixmp.objects.MsgScenario.commit(MsgScenario.java:1301)

**Comment by khaeru** [comment]
Closing this as it is two years stale and no additional information was provided.

If the error is still occurring, or recurs, please open a new issue, and specify the affected version(s) of ixmp.
